### ISSUE TITLE
Segmentation fault with high number of particles

### ISSUE THREAD

**Issue by vresbok** [treeppl/treeppl#19]
When I try to run my model with more than 150'000 particles I get the error
`segmentation fault `

i have tried increasing the stack size but get the same error. 

What could be the problem/solution here?

**Comment by vsenderov** [comment]
We need a little more information on how to reproduce, before the issue can be assessed.  Possibly a memory issue.

**Comment by vresbok** [comment]
Run the optmodel which is in the metabarcoding folder, with more than 150'000 particles. This causes the segmentation fault for me, and I need help finding the cause.

**Comment by vsenderov** [comment]
Are you and Jan currently working on this?  If not we need to discuss on Monday who can look into it.  Maybe you can even ask the Miking people as surely this is not front-end related (TreePPL), but also somehow I don't think it is CorePPL-related.  It seems you are reaching some hard memory limit (possibly stack size).

**Comment by vresbok** [comment]
Jan could look into it but has time constraints. Who do you suggest then, ViktorP is not available I guess?

**Comment by elegios** [comment]
One possible reason is related to #36, where it might be possible to use it to circumvent the type system (I *think* it shouldn’t be possible, but I can’t exclude the possibility), which would cause a segfault.

Running the program in gdb/lldb and printing the stack trace might be useful to localise the issue a bit. (Or using OCamls backtrace printing thing via an environment variable)

**Comment by vsenderov** [comment]
But do you think @elegios that the Segfault is indeed a problem (bug) and not just running out of memory?

**Comment by elegios** [comment]
I've never ended up running out of memory, but then again, I've not run nearly as large workloads. I'm merely saying it's another possibility.

**Comment by vresbok** [comment]
Jan has helped me resolve this issue. I needed to update my ocaml and owl packages, and now I do not have the error.
