### ISSUE TITLE
Deserialization of tensors doesn't work and converting tensors to sequences doesn't work

### ISSUE THREAD

**Issue by vsenderov** [treeppl/treeppl#21]
To read in tensors, we can't deserialize them from the model input:

```
model function tensors(magic: Tensor[Real]   ): Tensor[Real] {
//...
}
```

```
$ build/tpplc models/lang/tensors.tppl

ERROR <No file info>:
* Expected an expression of type: [Int] -> ([Int] -> Float) -> Tensor[Float]
* Found an expression of type: JsonValue
* When type checking the expression
```

However, we can _serialize_ them.

To input tensors, we need to use sequences and convert them.

The way around does not work: we cannot convert tensors to sequences either:

```
 let x = [1.0, 2.0, 3.0, 4.0, 5.0];
 let y = rvecCreate(5, x); // Creates a row vector
 // doesn't work
 let yy = vecToSeqExn(y);
```

```
ERROR </tmp/miking-tmp.QS4TOS0aZQ0 88049:28-88049:32>:
* Encountered a type variable escaping its scope: a32
* Perhaps the annotation of the associated let-binding is too general?
* When type checking the expression
                            t405
```

Summary: for input, we need to deserialize a sequence and convert it to a tensor; for output we serialize the tensor directly, but cannot convert it to a sequence.

**Comment by vsenderov** [comment]
This bug is getting problematic.  Apparently another thing that does not work is _serialization_ of user-defined types that do include tensors.

For example:

/** Test file for matrix syntaxes  -- DON'T CHANGE */
type TestType = TestType {
  multiplication: Tensor[Real],
  power: Tensor[Real]
}

```
model function tensors(): TestType {
  let m2 = mtxCreateId(5);
  let x = [1.0, 2.0, 3.0, 4.0, 5.0];
  let y = rvecCreate(5, x); // Creates a row vector 1 x 5
  let m2xY = y %*% m2  ; // (1 x 5) x (5 x 5) --> 1 x 5

  // Raising a matrix to an integer power -- P^n
  let m = mtxCreate(2, 2, [3.0, 0.0, -1.0, 7.0]);
  let m4 = m .^ 4;

  // Adding two matrices
  // NOTE(vsenderov, 23-09-29): addition only works as a function so we are not
  // testing

  return TestType {
    multiplication = m2xY,
    power = m4
  }
}
```

generates the error message:

```
ERROR <No file info>:
* Expected an expression of type: [Int] -> ([Int] -> Float) -> Tensor[Float]
* Found an expression of type: JsonValue
* When type checking the expression
```

@dlunde do you think you can take a look?

**Comment by vsenderov** [comment]
The current test-bed is https://github.com/vsenderov/treeppl/tree/tensors

**Comment by vsenderov** [comment]
We _can_ serialize regular user defined types that do not include tensors and we _can_ serialize simple tensors, i.e. if the return type is for example `Tensor[Real]`.

**Comment by dlunde** [comment]
I found and hopefully fixed the issue with deserialization (see the linked Miking PR). I did not find any issue with tensor serialization; the error message that you posted above is a result of the deserialization issue. Please test and see if the fix works before I debug further.

Regarding the "variable escaping its scope"-issue, I believe that this is due to what I mentioned in https://github.com/treeppl/treeppl/pull/16:
> I don't know what would cause the problems with externals. You're saying there is a problem in the CPPL compiler? Does the tpplc-produced cppl file look OK? I'm not sure calling buildMExpr is a good solution at the moment, didn't we experience some fundamental issue when using this approach (which is why we switched to outputting a CPPL file)?

I would suggest going back to the approach I implemented where we emit a CPPL file and compile that. We need to fix the externals issue that you (@vsenderov) mentioned (below, for reference), of course, but I believe that is not difficult.
> The externals didn't work any more. What we changed is that the command line now directly calls buildMExpr instead of emitting a CPPL file and compiling it through the system. If we do emit a CPPL file with mexprPPLToString and attempt to compile it, the cppl compiler will rename for example externalLog to externalLog1.

**Comment by vsenderov** [comment]
Re: tensor serialization.  The issue only appears when you serialize a user defined type (record) that contains a tensor.  I.e. something like:

```
  return TensorRecord {
    a = magicTensor,
    b = magicTensor
  };
```

But I suspect your fix will fix that as well as the error signatures are virtually identical.

There is a second thing in this issue, which I will probably need to spin out in a different bug report, which pertains to converting Tensors back to sequences, but that has nothing to do with Json seriazaliation/deserialization and will not be affected by your fix.

**Comment by vsenderov** [comment]
I will note your solution approach for the second issue (reverting to emitting cppl code, and compiling that).

**Comment by dlunde** [comment]
Let me know if the fix does not fix the serialization issue, and I'll debug further

**Comment by vsenderov** [comment]
For deserialization we have a workaround now 

```
function rvec2seq(t: Tensor[Real]): Real[] {
  let n = dim(t)[1]; 
  let myRng = 1 to n;
  let myFun = getRowVecElem(t); // currying
  let mySeq = sapply(myRng, myFun);
  return mySeq;
}

// TODO cvecToSeq
```

**Comment by dlunde** [comment]
> For deserialization we have a workaround now
> 
> ```
> function rvec2seq(t: Tensor[Real]): Real[] {
>   let n = dim(t)[1]; 
>   let myRng = 1 to n;
>   let myFun = getRowVecElem(t); // currying
>   let mySeq = sapply(myRng, myFun);
>   return mySeq;
> }
> 
> // TODO cvecToSeq
> ```

@vsenderov I thought I had fixed the deserialization issue? Is it still not working?

**Comment by vsenderov** [comment]
@dlunde  I mistyped.  This is about converting tensors to sequences.  I will change my wording above

**Comment by vsenderov** [comment]
I am closing this one, as we have a workaround for the one issue and a solution for the other. At some point it might be nice to go to the different compilation pipeline, which emits the cppl code and compiles that but not for the initial release.
