### ISSUE TITLE
Compiling error generated by PR #50

### ISSUE THREAD

**Issue by maribraga** [treeppl/treeppl#56]
After PR #50, I get the following error when trying to compile the host repertoire model

```
% tpplc host_repertoire.tppl -m smc-apf

ERROR <host_repertoire.tppl 115:44-115:55>:
* Encountered an unbound variable: categorical
* When type checking the expression
  let root_rep = sapply(probRecordSequence, categorical);
```

**Comment by vsenderov** [comment]
Indeed, I have introduced a regression that would have been caught by  `make test`. 

Note when merging PRs from now: run the tests!
