### ISSUE TITLE
Miking PR - Add binomial numbers related functions (#721) - breaks `tpplc`

### ISSUE THREAD

**Issue by vsenderov** [treeppl/treeppl#7]
```
$ tpplc models/diversification/crbd-new/crbd.tppl models/diversification/crbd-new/alcedinidae.mc out.mc

ERROR </home/viktor/.local/lib/mcore/stdlib/seq.mc 110:8-110:10>:
Unknown variable in symbolizeExpr: fb
  match fb with None _ then [] else
```

Using an older `mi` works, for example from 8d8902ac28fd316fcf1d86c012693a65ff971f78.

@elegios thinks that the solution is 

- to remove the filtering of externals in treeppl-to-coreppl/compile.mc and 
- update constructExternalMapH to traverse every Expr that has an inexpr

Removing the filtering of externals is quite easy: just comment lines 211-212.  This means that all externals parsed from "[ext.mc](http://ext.mc/)" will now be symbolized and available during compilation, but I suppose this is fine.

Then the error message changes to:

```
ERROR </home/viktor/.local/lib/mcore/stdlib/seq.mc 133:13-137:6>:
* Expected an expression of type: a -> c -> b -> a -> a -> [c] -> [b] -> a
* Found an expression of type: (a -> b -> c -> a) -> a -> [b] -> [c] -> a
* When type checking the expression
let foldl2 : all a. all b. all c. (a -> b -> c -> a) -> a -> [b] -> [c] -> a =
  lam f. lam acc. lam seq1. lam seq2.
    let g = lam acc : (a, [b]). lam x2.
      match acc with (acc, [x1] ++ xs1) in (f acc x1 x2, xs1)
    in
```
However, I don't get the second step,  "update constructExternalMapH to traverse every Expr that has an inexpr "
My thinking is that before, constructExternalMapH should be correctly traversing every Expr that has an inexpr, due to its recursive nature and the use of sfold_Expr_Expr . That's not correct?

**Comment by dlunde** [comment]
Yes, correct. Closing
